import {
  useMemo,
  useState,
} from 'react';

import type {
  FormEvent,
} from 'react';

import type {
  AnalyticsOverviewResponse,
  HotspotSummaryResponse,
  ReportCellValue,
  ReportDocument,
  ReportExportFormat,
  ReportSection,
  ReportTableColumn,
  ReportTableRow,
} from '@kavach/shared-types';

import './ReportsWorkspace.css';

type ReportKind =
  | 'case'
  | 'analytics'
  | 'hotspots';

type UnknownRecord =
  Record<
    string,
    unknown
  >;

interface DynamicColumn {
  key: string;

  label: string;

  paths:
    readonly (
      readonly string[]
    )[];
}

const REPORT_FORMATS:
readonly ReportExportFormat[] = [
  'pdf',
  'html',
  'json',
  'csv',
];

function isRecord(
  value: unknown,
): value is UnknownRecord {
  return (
    typeof value ===
      'object' &&
    value !== null &&
    !Array.isArray(value)
  );
}

function readPath(
  root: unknown,
  path:
    readonly string[],
): unknown {
  let current:
    unknown = root;

  for (
    const segment
    of path
  ) {
    if (!isRecord(current)) {
      return undefined;
    }

    current =
      current[segment];
  }

  return current;
}

function readFirstPath(
  root: unknown,
  paths:
    readonly (
      readonly string[]
    )[],
): unknown {
  for (
    const path
    of paths
  ) {
    const result =
      readPath(
        root,
        path,
      );

    if (
      result !== undefined &&
      result !== null &&
      result !== ''
    ) {
      return result;
    }
  }

  return null;
}

function readArray(
  root: unknown,
  paths:
    readonly (
      readonly string[]
    )[],
): unknown[] {
  const candidate =
    readFirstPath(
      root,
      paths,
    );

  return Array.isArray(
    candidate,
  )
    ? candidate
    : [];
}

function toCellValue(
  value: unknown,
): ReportCellValue {
  if (
    value === null ||
    value === undefined
  ) {
    return null;
  }

  if (
    typeof value ===
      'string' ||
    typeof value ===
      'number' ||
    typeof value ===
      'boolean'
  ) {
    return value;
  }

  if (Array.isArray(value)) {
    return value
      .map(
        (item) =>
          String(
            toCellValue(item) ??
            '',
          ),
      )
      .join(', ');
  }

  if (isRecord(value)) {
    const name =
      value.name ??
      value.label ??
      value.value;

    if (
      typeof name ===
        'string' ||
      typeof name ===
        'number'
    ) {
      return name;
    }

    return JSON.stringify(
      value,
    );
  }

  return String(value);
}

function createDynamicRows(
  rows:
    readonly unknown[],

  columns:
    readonly DynamicColumn[],
): ReportTableRow[] {
  return rows.map(
    (row) => {
      const result:
        ReportTableRow = {};

      columns.forEach(
        (column) => {
          result[column.key] =
            toCellValue(
              readFirstPath(
                row,
                column.paths,
              ),
            );
        },
      );

      return result;
    },
  );
}

function createColumns(
  columns:
    readonly DynamicColumn[],
): ReportTableColumn[] {
  return columns.map(
    (column) => ({
      key:
        column.key,

      label:
        column.label,
    }),
  );
}

function createReference(
  prefix: string,
): string {
  const timestamp =
    new Date()
      .toISOString()
      .replace(
        /[-:.TZ]/g,
        '',
      )
      .slice(0, 14);

  return [
    'KAVACH',
    prefix,
    timestamp,
  ].join('-');
}

function commonFooterNotes():
string[] {
  return [
    'Generated by KAVACH AI using synthetic demonstration data.',

    'The report provides investigative and analytical support only. Human verification is mandatory.',

    'Priority, similarity, hotspot and analytics outputs do not establish guilt, motive, conspiracy or criminal responsibility.',

    'This report must not be treated as an official police record, judicial finding or automated enforcement decision.',
  ];
}

async function buildCaseReport(
  caseId: number,
): Promise<ReportDocument> {
  const [
    detail,
    priority,
    similarity,
  ] =
    await Promise.all([
      window.kavach.cases
        .getById(caseId),

      window.kavach.priority
        .getCaseAssessment(
          caseId,
        ),

      window.kavach.similarity
        .getSimilarCases(
          caseId,
          {
            limit: 10,
            minimumScore: 20,
          },
        ),
    ]);

  const sections:
    ReportSection[] = [];

  sections.push({
    type:
      'key-value',

    title:
      'FIR Overview',

    items: [
      {
        label:
          'Case ID',

        value:
          toCellValue(
            readFirstPath(
              detail,
              [
                ['caseId'],
                ['caseMasterId'],
              ],
            ),
          ),
      },

      {
        label:
          'Crime number',

        value:
          toCellValue(
            readFirstPath(
              detail,
              [
                ['crimeNumber'],
                ['crimeNo'],
              ],
            ),
          ),
      },

      {
        label:
          'Registered date',

        value:
          toCellValue(
            readFirstPath(
              detail,
              [
                ['registeredDate'],
                ['crimeRegisteredDate'],
              ],
            ),
          ),
      },

      {
        label:
          'District',

        value:
          toCellValue(
            readFirstPath(
              detail,
              [
                [
                  'district',
                  'name',
                ],

                ['districtName'],
              ],
            ),
          ),
      },

      {
        label:
          'Police station',

        value:
          toCellValue(
            readFirstPath(
              detail,
              [
                [
                  'policeStation',
                  'name',
                ],

                ['policeStationName'],
              ],
            ),
          ),
      },

      {
        label:
          'Major crime head',

        value:
          toCellValue(
            readFirstPath(
              detail,
              [
                [
                  'majorCrimeHead',
                  'name',
                ],

                ['crimeMajorHeadName'],
              ],
            ),
          ),
      },

      {
        label:
          'Minor crime head',

        value:
          toCellValue(
            readFirstPath(
              detail,
              [
                [
                  'minorCrimeHead',
                  'name',
                ],

                ['crimeMinorHeadName'],
              ],
            ),
          ),
      },

      {
        label:
          'Gravity',

        value:
          toCellValue(
            readFirstPath(
              detail,
              [
                [
                  'gravity',
                  'name',
                ],

                ['gravityName'],
              ],
            ),
          ),
      },

      {
        label:
          'Case status',

        value:
          toCellValue(
            readFirstPath(
              detail,
              [
                [
                  'status',
                  'name',
                ],

                ['caseStatusName'],
              ],
            ),
          ),
      },
    ],
  });

  sections.push({
    type:
      'key-value',

    title:
      'Explainable Priority Assessment',

    items: [
      {
        label:
          'Priority score',

        value:
          priority.score,
      },

      {
        label:
          'Priority band',

        value:
          priority.band,
      },

      {
        label:
          'Rule version',

        value:
          priority.ruleVersion,
      },

      {
        label:
          'Human review required',

        value:
          priority
            .humanReviewRequired,
      },

      {
        label:
          'Assessment time',

        value:
          priority.assessedAt,
      },

      {
        label:
          'Permitted use',

        value:
          priority.permittedUse,
      },
    ],
  });

  sections.push({
    type: 'table',

    title:
      'Priority Factor Breakdown',

    columns: [
      {
        key: 'factor',
        label: 'Factor',
      },

      {
        key: 'rawValue',
        label: 'Raw Value',
      },

      {
        key: 'points',
        label: 'Points',
      },

      {
        key: 'maximum',
        label: 'Maximum',
      },

      {
        key: 'capped',
        label: 'Capped',
      },

      {
        key: 'explanation',
        label: 'Explanation',
      },
    ],

    rows:
      priority.factors.map(
        (factor) => ({
          factor:
            factor.label,

          rawValue:
            factor.rawValue,

          points:
            factor.points,

          maximum:
            factor
              .maximumAbsolutePoints,

          capped:
            factor.capped,

          explanation:
            factor.explanation,
        }),
      ),
  });

  sections.push({
    type: 'table',

    title:
      'Ranked Similar Cases',

    columns: [
      {
        key: 'caseId',
        label: 'Case ID',
      },

      {
        key: 'crimeNumber',
        label: 'Crime Number',
      },

      {
        key: 'score',
        label: 'Similarity',
      },

      {
        key: 'registeredDate',
        label: 'Registered Date',
      },

      {
        key: 'district',
        label: 'District',
      },

      {
        key: 'factors',
        label: 'Matching Factors',
      },
    ],

    rows:
      similarity.results.map(
        (result) => ({
          caseId:
            result.caseId,

          crimeNumber:
            result
              .caseSummary
              .crimeNumber,

          score:
            result
              .similarityScore,

          registeredDate:
            result
              .caseSummary
              .registeredDate,

          district:
            result
              .caseSummary
              .district
              .name,

          factors:
            result
              .matchingFactors
              .join(', '),
        }),
      ),
  });

  const timeline =
    readArray(
      detail,
      [
        ['timeline'],
        ['caseTimeline'],
      ],
    );

  if (
    timeline.length > 0
  ) {
    const timelineColumns:
      DynamicColumn[] = [
      {
        key: 'date',
        label: 'Date and Time',

        paths: [
          ['eventDateTime'],
          ['dateTime'],
          ['eventDate'],
        ],
      },

      {
        key: 'type',
        label: 'Event Type',

        paths: [
          ['eventType'],
          ['type'],
        ],
      },

      {
        key: 'description',
        label: 'Description',

        paths: [
          ['eventDescription'],
          ['description'],
        ],
      },

      {
        key: 'source',
        label: 'Source',

        paths: [
          ['sourceType'],
          ['source'],
        ],
      },
    ];

    sections.push({
      type: 'table',

      title:
        'Case Timeline',

      columns:
        createColumns(
          timelineColumns,
        ),

      rows:
        createDynamicRows(
          timeline,
          timelineColumns,
        ),
    });
  }

  const evidence =
    readArray(
      detail,
      [
        ['evidence'],
        ['evidenceItems'],
      ],
    );

  if (
    evidence.length > 0
  ) {
    const evidenceColumns:
      DynamicColumn[] = [
      {
        key: 'id',
        label: 'Evidence ID',

        paths: [
          ['evidenceId'],
          ['id'],
        ],
      },

      {
        key: 'type',
        label: 'Type',

        paths: [
          ['evidenceType'],
          ['type'],
        ],
      },

      {
        key: 'description',
        label: 'Description',

        paths: [
          ['description'],
        ],
      },

      {
        key: 'collected',
        label: 'Collected',

        paths: [
          ['collectedDateTime'],
          ['collectedAt'],
        ],
      },

      {
        key: 'reliability',
        label: 'Reliability',

        paths: [
          ['reliabilityScore'],
          ['reliability'],
        ],
      },
    ];

    sections.push({
      type: 'table',

      title:
        'Evidence Register',

      columns:
        createColumns(
          evidenceColumns,
        ),

      rows:
        createDynamicRows(
          evidence,
          evidenceColumns,
        ),
    });
  }

  const accused =
    readArray(
      detail,
      [
        ['accused'],
      ],
    );

  if (
    accused.length > 0
  ) {
    const accusedColumns:
      DynamicColumn[] = [
      {
        key: 'id',
        label: 'Accused ID',

        paths: [
          ['id'],
          ['accusedId'],
          ['accusedMasterId'],
        ],
      },

      {
        key: 'name',
        label: 'Name',

        paths: [
          ['name'],
          ['accusedName'],
        ],
      },

      {
        key: 'entityId',
        label: 'Resolved Entity',

        paths: [
          ['resolvedEntityId'],
          ['entityId'],
        ],
      },

      {
        key: 'status',
        label: 'Resolution Status',

        paths: [
          ['resolutionStatus'],
          ['status'],
        ],
      },
    ];

    sections.push({
      type: 'table',

      title:
        'Accused and Entity Resolution',

      columns:
        createColumns(
          accusedColumns,
        ),

      rows:
        createDynamicRows(
          accused,
          accusedColumns,
        ),
    });
  }

  return {
    title:
      'FIR Intelligence Report',

    subtitle:
      [
        'Explainable investigation summary',
        `for Case ${caseId}`,
      ].join(' '),

    reference:
      createReference(
        `CASE-${caseId}`,
      ),

    classification:
      'SYNTHETIC DEMONSTRATION DATA',

    generatedAt:
      new Date()
        .toISOString(),

    sections,

    footerNotes:
      commonFooterNotes(),
  };
}

function buildAnalyticsReport(
  analytics:
    AnalyticsOverviewResponse,
): ReportDocument {
  return {
    title:
      'Crime Analytics Report',

    subtitle:
      [
        'Descriptive FIR analytics from',
        analytics.query.registeredFrom,
        'to',
        analytics.query.registeredTo,
      ].join(' '),

    reference:
      createReference(
        'ANALYTICS',
      ),

    classification:
      'SYNTHETIC DEMONSTRATION DATA',

    generatedAt:
      new Date()
        .toISOString(),

    sections: [
      {
        type:
          'key-value',

        title:
          'Analytical Overview',

        items: [
          {
            label:
              'Registered cases',

            value:
              analytics
                .overview
                .totalCases,
          },

          {
            label:
              'Accused records',

            value:
              analytics
                .overview
                .accusedPersons,
          },

          {
            label:
              'Victim records',

            value:
              analytics
                .overview
                .victims,
          },

          {
            label:
              'Arrest events',

            value:
              analytics
                .overview
                .arrestEvents,
          },

          {
            label:
              'Arrest coverage',

            value:
              `${analytics.overview.arrestCoverageRate}%`,
          },

          {
            label:
              'Chargesheet coverage',

            value:
              `${analytics.overview.chargesheetCoverageRate}%`,
          },

          {
            label:
              'Average days to first arrest',

            value:
              analytics
                .overview
                .averageDaysToFirstArrest,
          },

          {
            label:
              'Average days to chargesheet',

            value:
              analytics
                .overview
                .averageDaysToFirstChargesheet,
          },
        ],
      },

      {
        type: 'table',

        title:
          'Monthly Investigation Cohorts',

        columns: [
          {
            key: 'period',
            label: 'Period',
          },

          {
            key: 'cases',
            label: 'Registered',
          },

          {
            key: 'arrests',
            label: 'With Arrest',
          },

          {
            key: 'chargesheets',
            label: 'With Chargesheet',
          },

          {
            key: 'arrestRate',
            label: 'Arrest Coverage',
          },

          {
            key: 'chargesheetRate',
            label: 'Chargesheet Coverage',
          },
        ],

        rows:
          analytics.monthlyTrend.map(
            (point) => ({
              period:
                point.period.label,

              cases:
                point.registeredCases,

              arrests:
                point.casesWithArrest,

              chargesheets:
                point
                  .casesWithChargesheet,

              arrestRate:
                `${point.arrestCoverageRate}%`,

              chargesheetRate:
                `${point.chargesheetCoverageRate}%`,
            }),
          ),
      },

      {
        type: 'table',

        title:
          'District Comparison',

        columns: [
          {
            key: 'district',
            label: 'District',
          },

          {
            key: 'cases',
            label: 'Cases',
          },

          {
            key: 'arrestRate',
            label: 'Arrest Coverage',
          },

          {
            key: 'chargesheetRate',
            label: 'Chargesheet Coverage',
          },
        ],

        rows:
          analytics
            .districtComparison
            .map(
              (district) => ({
                district:
                  district
                    .districtName,

                cases:
                  district
                    .totalCases,

                arrestRate:
                  `${district.arrestCoverageRate}%`,

                chargesheetRate:
                  `${district.chargesheetCoverageRate}%`,
              }),
            ),
      },

      {
        type: 'table',

        title:
          'Major Crime Composition',

        columns: [
          {
            key: 'classification',
            label: 'Classification',
          },

          {
            key: 'cases',
            label: 'Cases',
          },

          {
            key: 'percentage',
            label: 'Percentage',
          },
        ],

        rows:
          analytics
            .crimeComposition
            .map(
              (item) => ({
                classification:
                  item.name,

                cases:
                  item.count,

                percentage:
                  `${item.percentage}%`,
              }),
            ),
      },

      {
        type: 'table',

        title:
          'Recurring Modus Operandi',

        columns: [
          {
            key: 'name',
            label: 'Modus Operandi',
          },

          {
            key: 'cases',
            label: 'Cases',
          },

          {
            key: 'percentage',
            label: 'Percentage',
          },

          {
            key: 'confidence',
            label: 'Average Confidence',
          },
        ],

        rows:
          analytics
            .modusOperandiRecurrence
            .map(
              (item) => ({
                name:
                  item.name,

                cases:
                  item.caseCount,

                percentage:
                  `${item.percentage}%`,

                confidence:
                  item
                    .averageConfidence,
              }),
            ),
      },

      {
        type: 'text',

        title:
          'Methodology and Responsible Use',

        paragraphs: [
          analytics.methodology,
          analytics.responsibleUse,

          [
            'Excluded inputs:',
            analytics
              .excludedInputs
              .join(', '),
          ].join(' '),
        ],
      },
    ],

    footerNotes:
      commonFooterNotes(),
  };
}

function buildHotspotReport(
  hotspots:
    HotspotSummaryResponse,
): ReportDocument {
  return {
    title:
      'Hotspot Intelligence Report',

    subtitle:
      [
        'Historical aggregate location',
        'analysis for',
        hotspots.period.label,
      ].join(' '),

    reference:
      createReference(
        `HOTSPOT-${hotspots.period.key}`,
      ),

    classification:
      'SYNTHETIC DEMONSTRATION DATA',

    generatedAt:
      new Date()
        .toISOString(),

    sections: [
      {
        type:
          'key-value',

        title:
          'Period Summary',

        items: [
          {
            label:
              'Reporting period',

            value:
              hotspots
                .period
                .label,
          },

          {
            label:
              'Matching locations',

            value:
              hotspots
                .matchingLocations,
          },

          {
            label:
              'Total monthly cases',

            value:
              hotspots
                .totalCrimeCount,
          },

          {
            label:
              'Average pressure',

            value:
              hotspots
                .averagePressureScore,
          },

          {
            label:
              'Critical locations',

            value:
              hotspots
                .criticalLocationCount,
          },

          {
            label:
              'High locations',

            value:
              hotspots
                .highLocationCount,
          },
        ],
      },

      {
        type: 'table',

        title:
          'Ranked Locations',

        columns: [
          {
            key: 'rank',
            label: 'Rank',
          },

          {
            key: 'location',
            label: 'Location',
          },

          {
            key: 'district',
            label: 'District',
          },

          {
            key: 'station',
            label: 'Police Station',
          },

          {
            key: 'score',
            label: 'Pressure',
          },

          {
            key: 'band',
            label: 'Band',
          },

          {
            key: 'cases',
            label: 'Cases',
          },

          {
            key: 'trend',
            label: 'Trend',
          },

          {
            key: 'crime',
            label: 'Dominant Crime',
          },
        ],

        rows:
          hotspots.items.map(
            (
              item,
              index,
            ) => ({
              rank:
                index + 1,

              location:
                item.location.name,

              district:
                item
                  .location
                  .district
                  .name,

              station:
                item
                  .location
                  .policeStation
                  .name,

              score:
                item.pressureScore,

              band:
                item.riskBand,

              cases:
                item.crimeCount,

              trend:
                item.trendDirection,

              crime:
                item
                  .dominantCrimeType,
            }),
          ),
      },

      {
        type: 'text',

        title:
          'Methodology and Responsible Use',

        paragraphs: [
          hotspots.methodology,
          hotspots.responsibleUse,

          [
            'Excluded inputs:',
            hotspots
              .excludedInputs
              .join(', '),
          ].join(' '),
        ],
      },
    ],

    footerNotes:
      commonFooterNotes(),
  };
}

function formatPreviewValue(
  value:
    ReportCellValue,
): string {
  if (value === null) {
    return '—';
  }

  if (
    typeof value ===
      'boolean'
  ) {
    return value
      ? 'Yes'
      : 'No';
  }

  return String(value);
}

function createSuggestedFileName(
  document:
    ReportDocument,
): string {
  return document.reference
    .toLowerCase();
}

export function ReportsWorkspace() {
  const [
    reportKind,
    setReportKind,
  ] =
    useState<ReportKind>(
      'case',
    );

  const [
    caseIdInput,
    setCaseIdInput,
  ] =
    useState('1');

  const [
    document,
    setDocument,
  ] =
    useState<
      ReportDocument |
      null
    >(null);

  const [
    loading,
    setLoading,
  ] =
    useState(false);

  const [
    error,
    setError,
  ] =
    useState<string | null>(
      null,
    );

  const [
    exportMessage,
    setExportMessage,
  ] =
    useState<string | null>(
      null,
    );

  const [
    exportingFormat,
    setExportingFormat,
  ] =
    useState<
      ReportExportFormat |
      null
    >(null);

  const reportDescription =
    useMemo(
      () => {
        switch (reportKind) {
          case 'analytics':
            return [
              'Dataset-wide crime trends,',
              'district comparisons,',
              'investigation milestones and',
              'modus-operandi recurrence.',
            ].join(' ');

          case 'hotspots':
            return [
              'Historical location pressure,',
              'jurisdiction details and',
              'ranked aggregate hotspots.',
            ].join(' ');

          default:
            return [
              'FIR details, explainable',
              'priority, similar cases,',
              'timeline and evidence.',
            ].join(' ');
        }
      },
      [
        reportKind,
      ],
    );

  async function generateReport(
    event:
      FormEvent<HTMLFormElement>,
  ): Promise<void> {
    event.preventDefault();

    setLoading(true);
    setError(null);
    setExportMessage(null);

    try {
      if (
        reportKind ===
          'case'
      ) {
        const caseId =
          Number(
            caseIdInput,
          );

        if (
          !Number.isSafeInteger(
            caseId,
          ) ||
          caseId < 1
        ) {
          throw new Error(
            'Case ID must be a positive integer.',
          );
        }

        setDocument(
          await buildCaseReport(
            caseId,
          ),
        );
      } else if (
        reportKind ===
          'analytics'
      ) {
        const analytics =
          await window.kavach
            .analytics
            .getOverview();

        setDocument(
          buildAnalyticsReport(
            analytics,
          ),
        );
      } else {
        const hotspots =
          await window.kavach
            .hotspots
            .getSummary({
              limit: 50,
            });

        setDocument(
          buildHotspotReport(
            hotspots,
          ),
        );
      }
    } catch (
      generationError: unknown
    ) {
      setDocument(null);

      setError(
        generationError instanceof
          Error
          ? generationError.message
          : 'The report could not be generated.',
      );
    } finally {
      setLoading(false);
    }
  }

  async function exportDocument(
    format:
      ReportExportFormat,
  ): Promise<void> {
    if (!document) {
      return;
    }

    setExportingFormat(
      format,
    );

    setError(null);
    setExportMessage(null);

    try {
      const response =
        await window.kavach
          .reports
          .exportDocument({
            format,

            suggestedFileName:
              createSuggestedFileName(
                document,
              ),

            document,
          });

      if (
        response.cancelled
      ) {
        setExportMessage(
          'Export cancelled.',
        );
      } else {
        setExportMessage(
          `Report saved to ${response.filePath}`,
        );
      }
    } catch (
      exportError: unknown
    ) {
      setError(
        exportError instanceof
          Error
          ? exportError.message
          : 'The report could not be exported.',
      );
    } finally {
      setExportingFormat(
        null,
      );
    }
  }

  return (
    <section
      className="reports-workspace"
      aria-labelledby="reports-workspace-title"
    >
      <header className="reports-workspace__header">
        <div>
          <span className="reports-workspace__eyebrow">
            CONTROLLED INTELLIGENCE EXPORT
          </span>

          <h2 id="reports-workspace-title">
            Reports and Exports
          </h2>

          <p>
            Generate reviewable intelligence
            documents and export them through
            the secured Electron main process.
          </p>
        </div>

        <div className="reports-workspace__status">
          <span
            aria-hidden="true"
          />

          LOCAL EXPORT CONTROL
        </div>
      </header>

      <aside className="reports-workspace__governance">
        <div
          className="reports-workspace__governance-mark"
          aria-hidden="true"
        >
          !
        </div>

        <div>
          <strong>
            Synthetic demonstration data
          </strong>

          <p>
            Exported reports are investigative
            support documents. They are not
            official police records, legal
            findings or automated enforcement
            decisions.
          </p>
        </div>
      </aside>

      <form
        className="report-builder"
        onSubmit={generateReport}
      >
        <div className="report-builder__heading">
          <div>
            <span>
              REPORT CONFIGURATION
            </span>

            <h3>
              Build intelligence document
            </h3>
          </div>
        </div>

        <div className="report-builder__types">
          <button
            type="button"
            className={
              reportKind ===
                'case'
                ? 'report-type report-type--active'
                : 'report-type'
            }
            aria-pressed={
              reportKind ===
              'case'
            }
            onClick={() =>
              setReportKind(
                'case',
              )
            }
          >
            <strong>
              FIR Intelligence
            </strong>

            <span>
              Priority, similarity,
              timeline and evidence
            </span>
          </button>

          <button
            type="button"
            className={
              reportKind ===
                'analytics'
                ? 'report-type report-type--active'
                : 'report-type'
            }
            aria-pressed={
              reportKind ===
              'analytics'
            }
            onClick={() =>
              setReportKind(
                'analytics',
              )
            }
          >
            <strong>
              Crime Analytics
            </strong>

            <span>
              Trends, outcomes and
              jurisdiction comparisons
            </span>
          </button>

          <button
            type="button"
            className={
              reportKind ===
                'hotspots'
                ? 'report-type report-type--active'
                : 'report-type'
            }
            aria-pressed={
              reportKind ===
              'hotspots'
            }
            onClick={() =>
              setReportKind(
                'hotspots',
              )
            }
          >
            <strong>
              Hotspot Intelligence
            </strong>

            <span>
              Ranked locations and
              aggregate pressure
            </span>
          </button>
        </div>

        <p className="report-builder__description">
          {reportDescription}
        </p>

        <div className="report-builder__controls">
          {reportKind ===
            'case' && (
            <label>
              <span>
                Case ID
              </span>

              <input
                type="number"
                min="1"
                step="1"
                value={
                  caseIdInput
                }
                disabled={
                  loading
                }
                onChange={(event) =>
                  setCaseIdInput(
                    event.target.value,
                  )
                }
              />
            </label>
          )}

          <button
            type="submit"
            disabled={loading}
          >
            {loading
              ? 'Generating report…'
              : 'Generate report'}
          </button>
        </div>
      </form>

      {error && (
        <div
          className="reports-workspace__error"
          role="alert"
        >
          <strong>
            Report operation failed
          </strong>

          <span>{error}</span>
        </div>
      )}

      {exportMessage && (
        <div className="reports-workspace__success">
          {exportMessage}
        </div>
      )}

      {!document && (
        <div className="reports-workspace__empty">
          <strong>
            No report generated
          </strong>

          <span>
            Select a report type and generate
            a preview before exporting.
          </span>
        </div>
      )}

      {document && (
        <>
          <div className="report-export-bar">
            <div>
              <span>
                EXPORT GENERATED REPORT
              </span>

              <strong>
                {document.reference}
              </strong>
            </div>

            <div>
              {REPORT_FORMATS.map(
                (format) => (
                  <button
                    key={format}
                    type="button"
                    disabled={
                      exportingFormat !==
                      null
                    }
                    onClick={() =>
                      void exportDocument(
                        format,
                      )
                    }
                  >
                    {exportingFormat ===
                    format
                      ? 'Saving…'
                      : `Export ${format.toUpperCase()}`}
                  </button>
                ),
              )}
            </div>
          </div>

          <article className="report-preview">
            <header>
              <span>
                KAVACH AI · CRIME INTELLIGENCE
              </span>

              <h3>
                {document.title}
              </h3>

              <p>
                {document.subtitle}
              </p>

              <div className="report-preview__metadata">
                <div>
                  <span>
                    Reference
                  </span>

                  <strong>
                    {
                      document
                        .reference
                    }
                  </strong>
                </div>

                <div>
                  <span>
                    Generated
                  </span>

                  <strong>
                    {
                      document
                        .generatedAt
                    }
                  </strong>
                </div>

                <div>
                  <span>
                    Classification
                  </span>

                  <strong>
                    {
                      document
                        .classification
                    }
                  </strong>
                </div>
              </div>
            </header>

            <div className="report-preview__synthetic">
              Synthetic demonstration data.
              Not an official police record
              or legal determination.
            </div>

            {document.sections.map(
              (
                section,
                sectionIndex,
              ) => (
                <section
                  key={[
                    section.title,
                    sectionIndex,
                  ].join(':')}
                  className="report-preview__section"
                >
                  <h4>
                    {section.title}
                  </h4>

                  {section.type ===
                    'text' &&
                    section.paragraphs.map(
                      (
                        paragraph,
                        paragraphIndex,
                      ) => (
                        <p
                          key={[
                            paragraphIndex,
                            paragraph,
                          ].join(':')}
                        >
                          {paragraph}
                        </p>
                      ),
                    )}

                  {section.type ===
                    'key-value' && (
                    <div className="report-preview__key-values">
                      {section.items.map(
                        (
                          item,
                          itemIndex,
                        ) => (
                          <article
                            key={[
                              item.label,
                              itemIndex,
                            ].join(':')}
                          >
                            <span>
                              {item.label}
                            </span>

                            <strong>
                              {formatPreviewValue(
                                item.value,
                              )}
                            </strong>
                          </article>
                        ),
                      )}
                    </div>
                  )}

                  {section.type ===
                    'table' && (
                    <div className="report-preview__table-shell">
                      <table>
                        <thead>
                          <tr>
                            {section.columns.map(
                              (column) => (
                                <th
                                  key={
                                    column.key
                                  }
                                >
                                  {
                                    column
                                      .label
                                  }
                                </th>
                              ),
                            )}
                          </tr>
                        </thead>

                        <tbody>
                          {section.rows.length ===
                            0 && (
                            <tr>
                              <td
                                colSpan={
                                  section
                                    .columns
                                    .length
                                }
                                className="report-preview__no-rows"
                              >
                                No records available.
                              </td>
                            </tr>
                          )}

                          {section.rows
                            .slice(
                              0,
                              100,
                            )
                            .map(
                              (
                                row,
                                rowIndex,
                              ) => (
                                <tr
                                  key={
                                    rowIndex
                                  }
                                >
                                  {section.columns.map(
                                    (
                                      column,
                                    ) => (
                                      <td
                                        key={
                                          column
                                            .key
                                        }
                                      >
                                        {formatPreviewValue(
                                          row[
                                            column
                                              .key
                                          ],
                                        )}
                                      </td>
                                    ),
                                  )}
                                </tr>
                              ),
                            )}
                        </tbody>
                      </table>

                      {section.rows.length >
                        100 && (
                        <div className="report-preview__truncated">
                          Preview shows the first
                          100 rows. The export
                          includes all{' '}
                          {
                            section
                              .rows
                              .length
                          }{' '}
                          rows.
                        </div>
                      )}
                    </div>
                  )}
                </section>
              ),
            )}

            <footer>
              {document.footerNotes.map(
                (
                  note,
                  noteIndex,
                ) => (
                  <p
                    key={[
                      noteIndex,
                      note,
                    ].join(':')}
                  >
                    {note}
                  </p>
                ),
              )}
            </footer>
          </article>
        </>
      )}
    </section>
  );
}
